namespace Domain
{
    public class Value
    {
        // in code first db generation this will produce an autogenerated primary key field
        public int Id { get; set; }
        public string Name { get; set; }
    }
}
